---
- hosts: webservers
  become: yes
  become_method: sudo
  tasks:
  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes

  - name: install packages
    apt: name={{item}} state=present
    with_items:
      - python3-pip
      - python3-dev
      - python3.8-venv
      - unzip
      - golang-go

# Install the app, note: don't do these tasks with become sudo
- hosts: webservers
  tasks:
  - name: clone repo
    git:
      repo: 'https://github.com/shantnu/sentiment-duck.git'
      dest: /home/ubuntu/sentiduck
      update: yes  # Does a git pull if the repo already exists
  - name: install modules in a virtualenv
    pip:
      requirements: /home/ubuntu/sentiduck/requirements.txt
      virtualenv: /home/ubuntu/sentiduck/env
      virtualenv_command: 'python3 -m venv'

- hosts: webservers
  tasks:
  - name: Install NLTK Data
    shell: "/home/ubuntu/sentiduck/env/bin/python -m nltk.downloader vader_lexicon"

# Install caddy
- hosts: webservers
  become: yes
  become_method: sudo
  tasks:
    - ansible.builtin.script: ./install_caddy.sh


# install aws cli
- hosts: webservers
  vars_files:
      - vars/pass.yml
  tasks:
  - name: Download the awscli bundle.
    get_url: url=https://s3.amazonaws.com/aws-cli/awscli-bundle.zip dest=/tmp/awscli-bundle.zip
    register: aws_cli_download_bundle

  - name: Unarchive the installer.
    unarchive: src=/tmp/awscli-bundle.zip dest=/tmp copy=no creates=/tmp/awscli-bundle
    register: aws_cli_unarchive_installer

  - name: Install awscli package.
    shell: sudo python3 /tmp/awscli-bundle/install -i /usr/local/aws -b /usr/bin/aws
    args:
      creates: /usr/bin/aws

  - name: Configure AWS.
    shell: aws configure set {{ item.key }} {{ item.value }} --profile {{ aws_profile }}
    no_log: True
    with_dict:
      region: "{{ aws_region }}"
      aws_access_key_id: "{{ aws_access_key_id }}"
      aws_secret_access_key: "{{ aws_secret_access_key }}"
      format: "{{ aws_format }}"


# Copy praw file
- hosts: webservers

  tasks:

  - name: Copy praw file
    copy:
      src: ./praw.ini
      dest: /home/ubuntu/sentiduck/praw.ini

- hosts: webservers
  tasks:
  - cron:
      name: cron to update dynamodb
      minute: "0"
      hour: "23"
      job: "cd /home/ubuntu/sentiduck; /home/ubuntu/sentiduck/env/bin/python main.py"

# Configure app systemd service
- hosts: webservers
  become: yes
  become_method: sudo
  tasks:
  - name: Build go code
    shell: cd /home/ubuntu/sentiduck/go_app; go build -o senti_server
  - name: template systemd service config
    copy:
      src: .service
      dest: /etc/systemd/system/sentiduck.service
  - name: start systemd app service
    systemd: name=sentiduck.service state=restarted enabled=yes

# # Run a quick test to verify the site is working
- hosts: webservers
  tasks:
  - name: Check that a page returns a status 200
    uri:
      url: https://sentimentduck.com/
      return_content: yes
    register: this
    failed_when: "'Comparing UK Reddit' not in this.content"
